# Используйте официальный образ Node.js как базовый
FROM node:14

# Установите рабочую директорию в контейнере
WORKDIR /usr/src/app

# Копируйте файлы package.json и package-lock.json
COPY package*.json ./

# Установите зависимости проекта
RUN npm install

# Копируйте исходный код проекта в контейнер
COPY . .

# Соберите приложение
RUN npm run build

# Откройте порт, на котором работает ваше приложение
EXPOSE 3000

# Запуск приложения
CMD ["node", "dist/main"]
